# Lecture 1) Basics to work with Python

In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import sklearn as sl
%matplotlib inline
import scipy as sc
import math as ma
from scipy import linalg, optimize, constants, interpolate, special, stats
from math import exp, pow, sqrt, log

import seaborn as sns #special Graphics tools
import statsmodels.api as sm
import statsmodels.stats.api as sms

# 1.) First Steps

Python can be used directly from the console. 

Commands can be entered directly, or scripts created in a text editor can be called and executed. However, it is more organized to use a notebook environment. 

We use Jupyter as our notebook environment.

## 1.1) Installing Jupyter

If you have installed Python on your computer, you should first install the Python installer PIP.
PIP can be used to install all necessary Python packages from the console. PIP is usually included with the Python installation. To work with the latest available version, you should run an upgrade (in the console):

WINDOWS: 

    python -m pip install -U pip setuptools

Mac or LINUX: 

    pip install -U pip setuptools

You can then easily install Jupyter with the command:

Python2: pip install jupyter
-> (Python3: pip3 install jupyter)

Any other additional package can be installed using PIP with the command:

    pip install "PackageName"

You can start Jupyter from the console with the command:

    jupyter notebook
 

## 1.2) Calculating with Python

In the command line, you can directly define variables and perform calculations.
You can add comments using the symbol # to document the code.

The cell is executed when you press the "Play" button in the toolbar (there are also shortcuts depending on your Laptop).

In the toolbar, you will also find options from right to left: "save," "add cell below," "cut selected cell," etc.




...a first example

In [2]:
a = 1 #Define the variable a and assign the value 1.
b = 2 #Define the variable b and assign the value 2.

a**2+b**2 #calculate a^2+b^2

c = a**2 + b**2

...the cell has now been evaluated. 

By default, the output is suppressed. If you want to see the result for c, for example, it must be entered.

In [3]:
c

5

Python has different number formats:

- int
- float
- complex

In [4]:
type(c) #Integer


int

In [5]:
a = 1.5 + 0.5j #complex number
type(a)

complex

In [6]:
a.real #real part

1.5

In [7]:
a.imag #imaginary part

0.5

In [8]:
d = 2. #Float                                                               

In [9]:
type(d)

float

In [10]:
3 < 4 #Bool operator 
test = (3 < 4)

test 

True

In [11]:
type(test)

bool

The Jupyter Notebook can be used like a calculator.
Arithmetic operations: +, -, *, /, %


In [12]:
2/3

0.6666666666666666

### Exercise 1)

Define a complex number. 
Calculate the real part and the imaginary part, and display the results in different numerical formats.
            

## 1.3) Functions in Python

First, the name of the function is created, and the variables are defined.
Then, the function definition is established.

It is important to note that indentation is required.

In [13]:
def f(x): #area of a circle as function of the radius
    return 3.14 * x * x #mapping

In [14]:
f(1.5)

7.0649999999999995

In [15]:
def double(x):
     return 2*x

In [16]:
double(3)

6

### Exercise 2) 
    
Define the function  

$f(x,y)=2+x^2+3y^2$

Evaluate the function at various points 
(x,y).   

Example:

    def f(x,y):
    return 2+x+3*y
    
    f(1,1)

## 1.4) Special Functions

The "math" package can be used...  
Special function definitions must be imported from the math package before use.
                          

In [17]:
from math import exp, pow, sqrt, log

In [18]:
exp(3) # e**x

20.085536923187668

In [19]:
pow(2,3) #x**y 

8.0

In [20]:
sqrt(9) #root x

3.0

In [21]:
log(2) #Logarithm with basis e - natural Logarithm

0.6931471805599453

In [22]:
log(2,10) #Logarithm with arbitrary basis - here basis 10

0.30102999566398114

Trigonometric Functions (Argument in rad)

In [23]:
from math import cos, sin, tan

In [24]:
cos(3.14)

-0.9999987317275395

In [25]:
sin(3.14)

0.0015926529164868282

In [26]:
tan(-2*3.14)

0.003185317952531891

...you can switch from rad to deg and back again :-) ...

In [27]:
from math import degrees, radians

In [28]:
degrees(3.141592653589793) #calculate Pi in deg

180.0

In [29]:
radians(180) #calculate 180° in rad

3.141592653589793

Important mathematical constants can also be imported as symbols.

In [30]:
from math import pi, e

In [31]:
pi # Pi

3.141592653589793

In [32]:
e #transcendent number e

2.718281828459045

In [33]:
sin(pi) #sin(Pi) as float

1.2246467991473532e-16

In [34]:
int(sin(pi)) #sin(pi) as Integer

0

In [35]:
cos(pi/2) #cos(Pi/2) as float

int(cos(pi/2)) #as Integer

0

trigonometric Functions: 

- cos(x)
- sin(x)
- tan(x) 
- acos(x) (arc cos) 
- asin(x) (arc sin)
- atan(x) (arc tan)

hyperbolic Functions:  
    
- cosh(x)
- sinh(x)
- tanh(x)
- acosh(x)
- asinh(x)
- atanh(x)  

### Exercise 3)

- Define a function that calculates the magnitude of a complex number and test the function with an example.

- Define two functions that calculate the angle between two vectors (a1,a2) and (b1, b2) in the first quadrant, once in radians and once in degrees.

- Apply the functions to the vectors (0,1) and (1,1)

- Define a function that calculates the distance between two points in $\mathbb{R}^2$

- Apply the function to the points (0,1) and (1,0).

In [36]:
from math import acos
def rad_winkel(a1,a2,b1,b2):
         return acos((a1*b1+a2*b2)/(sqrt(a1**2+a2**2)*sqrt(b1**2+b2**2)))
                               

In [37]:
a = rad_winkel(0,1,1,1) 
a                               

0.7853981633974484

In [38]:
from math import acos, degrees 

def grad_winkel(a1,a2,b1,b2):
         return degrees(acos((a1*b1+a2*b2)/(sqrt(a1**2+a2**2)*sqrt(b1**2+b2**2))))
                               

In [39]:
a = grad_winkel(0,1,1,1) 
a

45.00000000000001

In [40]:
def distance(a1,a2,b1,b2):
     return sqrt((-a1+b1)**2+(-a2+b2)**2)

In [41]:
a = distance(0,1,1,0)
a

1.4142135623730951

# 2) Arrays – NumPy

The NumPy package is a Python extension particularly suited for handling matrices (arrays).
It also allows for working with multi-dimensional arrays.
Advantages:

- Closer to the hardware (efficiency)
- Designed for scientific computation
- Array-oriented computing

The package must be loaded first to utilize all functionalities...
The recommended way to import NumPy is:

    import numpy as np

-> Theoretically, you can assign a different name,
(which is not advisable if you want to use/recycle code from the internet, as it typically assumes this convention).

-> A similar situation applies to other packages like Pandas (more on that later...).

In [42]:
import numpy as np

In [43]:
a = np.array([0, 1, 2, 3]) #define a Numpy array, containing the numbers 0,1,2,3
a

array([0, 1, 2, 3])

Arrays can contain:

- Data from experiments/simulations at discrete time steps
- Signals recorded from measuring instruments, e.g., sound waves
- Pixels of an image, gray-level or color
- 3-D data measured at different X-Y-Z positions, e.g., MRI scans
...

With 

    np.array

you can access the documentation for arrays in NumPy...





## 2.1) Generating Arrays  

- 1-D:

In [44]:
a = np.array([0, 1, 2, 3]) 
a

array([0, 1, 2, 3])

In [45]:
a.ndim #show dimension

1

In [46]:
len(a) #Length

4

In [47]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array

In [48]:
b.ndim #Dimensions

2

In [49]:
b.shape #Form

(2, 3)

In [50]:
len(b) # length of 1st Dimension

2

In [51]:
a.shape #infos about structure

(4,)

Arrays in 2-D, 3-D, ...:

In [52]:
b = np.array([[0, 1, 2], [3, 4, 5]]) # 2 x 3 array
b

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
b.shape
b.ndim
len(b)

2

In [54]:
c = np.array([[[1], [2]], [[3], [4]]]) #complex Array 
c

array([[[1],
        [2]],

       [[3],
        [4]]])

## 2.2) Methods for Generating Arrays

Normally, you will rarely define the entries of an array by hand.
Either data is read in, or specific arrays are generated. Here are some examples:

### 2.2.1) Integer entries

In [55]:
a = np.arange(10) # 0 .. n-1 (!) - Python starts counting with 0!!!
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b = np.arange(1, 11, 3) # start, end (exclusive), step size b
b

array([ 1,  4,  7, 10])

### 2.2.2) Number of points in an interval

In [57]:
c = np.linspace(0, 1, 6) # start, end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [58]:
d = np.linspace(0, 1, 5, endpoint=True)
d

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 2.2.3) special Arrays

In [59]:
a = np.ones((3, 3)) # reminder: (3, 3) is a tuple - complete array with ones 
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
b = np.zeros((2, 2)) #complete Array with zeros
b

array([[0., 0.],
       [0., 0.]])

In [61]:
c = np.eye(3) #Identity matrix 
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
d = np.diag(np.array([1, 2, 3, 4])) #diagonal matrix
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 2.2.4.) Arrays with random numbers

In [63]:
a = np.random.rand(10) # uniform in [0, 1] - random numbers from uniform distribution
a

array([0.79606147, 0.82258606, 0.2326305 , 0.94098792, 0.48462037,
       0.99973693, 0.99323037, 0.64744986, 0.03671612, 0.01840437])

In [64]:
b = np.random.randn(4) # standard normal distribution
b

array([ 0.61351442, -0.33769388,  0.28107308, -2.23230617])

In [65]:
np.random.seed(1234) # Setting the random seed - makes it reproducible

b = np.random.randn(4) # standard normal distribution
b

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ])

In [66]:
b = np.random.randn(4) # standard normal distribution
b

array([-0.72058873,  0.88716294,  0.85958841, -0.6365235 ])

### Exercise 4) Generating Arrays Using Specific Functions

- Experiment with arange, linspace, ones, zeros, eye, and diag.
- Create different arrays with random numbers.
- Set the seed before generating an array with random numbers.
- Test the function np.empty. What happens? When might this be useful?

In [67]:
#Data types in the array can be queried using dtype – default is Integer if specified as such.

a = np.array([1, 2, 3]) 
a.dtype

dtype('int64')

In [68]:
c = np.array([1, 2, 3], dtype=float) #data type can be specified explicitely 
c.dtype

dtype('float64')

default data type is float:

In [69]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

Arithmetic operations are performed element-wise on arrays 

Note: dimensions must match!!

In [70]:
 
a = np.ones((3, 3))
b = np.diag(np.array([1, 2, 3])) #diagonal matrix
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
c = a*2 #Multiplication with a scalar
c

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [72]:
a+b #elementwise addition

array([[2., 1., 1.],
       [1., 3., 1.],
       [1., 1., 4.]])

In [73]:
b*b #elementwise multiplication

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [74]:
2*a+(b*c) #combined operation

array([[4., 2., 2.],
       [2., 6., 2.],
       [2., 2., 8.]])

### Exercise 5)  

Calculate the elementwise product a*b for 

    a = np.ones((3, 3)) 
    
and 

    b = np.diag(np.array([1, 2, 3, 4])) 

## 2.3) The NumPy matrix class - a specialized 2D array numpy.matrix

'Returns a matrix from an array-like object or from a string of data. 

A matrix is a specialized 2-D array that retains its 2-D nature through operations. 

It has certain special operators, such as * (matrix multiplication) and ** (matrix power).'

In [75]:
A = np.matrix('1 2; 3 4') #2x2 matrix with special entries
A

matrix([[1, 2],
        [3, 4]])

In [76]:
print(A) #shows elements

[[1 2]
 [3 4]]


In [77]:
np.matrix([[1, 2], [3, 4]]) #other possibility to define the matrix

matrix([[1, 2],
        [3, 4]])

In [78]:
A = np.matrix('1 2; 3 4') #define A and B
B = np.matrix('5 6; 7 8')
A*B #calculate the matrix product

matrix([[19, 22],
        [43, 50]])

For the matrix class, there are many special functions, such as forming the transpose, calculating the conjugate complex, etc.

In [79]:
A.getT() #Transposed Matrix

matrix([[1, 3],
        [2, 4]])

### Exercise 6)  

- Define two arrays and compute their product. 
- Is there a difference in the result if you define the two arrays as matrices and then calculate the product?


## 2.4) Accessing elements of matrices and arrays

In [80]:
A = np.matrix('1 2 3 4 5; 6 7 8 9 10') #define Matrix
B = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]]) #Define the same matrix as array
A

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [81]:
A[1,3] #second Element in first row - python starts to count with 0!!!

9

In [82]:
print (A[0,:]) #all elements of first row
print (A[1,:])  #all elements of second row
print (A[:,0])  #all elements of first column
print (A[0,2:4]) #Elements 3 to 4 - The right endpoint of the interval is excluded

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]
[[1]
 [6]]
[[3 4]]


In [83]:
print (B[0,2:5]) #same for arrays

[3 4 5]


In [84]:
C = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15],[16, 17, 18,19, 20]]) #define large array
print (C[1:4,2:5]) #easy to get subsets

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


# 3) Linear Algebra with NumPy

NumPy is capable of performing many different operations with arrays (matrices). Examples include:

- Calculating the determinant
- Calculating the inverse
- Computing the Cholesky decomposition
- Solving linear systems
...
For this, the NumPy package 'linalg' is used...

In [85]:
a = np.array([[1, 2], [3, 4]]) #2x2 Matrix: Det(A)=ad-bc 
np.linalg.det(a)

-2.0000000000000004

In [86]:
a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ]) 
a.shape 
np.linalg.det(a)

array([-2., -3., -8.])